package com.banking.controller;

import com.banking.dao.TransactionDao;
import com.banking.model.Account;
import com.banking.model.User;
import com.banking.utils.CustomException;
import com.banking.utils.ErrorMessages;
import com.banking.utils.InputValidator;

public class TransactionController {

	private TransactionDao transactionDao;
	//private AccountDao accountDao;

	public TransactionController(TransactionDao transactionDao) {
		this.transactionDao = transactionDao;
		//this.accountDao = new AccountDaoImplementation();
	}

	public boolean depositAmount(User user, Account selectedAccount, double amountToDeposite) throws CustomException {
		InputValidator.isNull(selectedAccount, ErrorMessages.INPUT_NULL_MESSAGE);
		InputValidator.isNull(user,ErrorMessages.INPUT_NULL_MESSAGE);
		boolean isDepositeSuccess = false;
		try {
			isDepositeSuccess = transactionDao.deposit(user,selectedAccount,amountToDeposite);
		}catch(Exception e) {
			throw new CustomException("Error while Depositing Money!!",e);
		}
		return isDepositeSuccess;
	}

	public boolean withdrawAmount(User user, Account selectedAccount, double amountToWithdraw) throws CustomException {
		InputValidator.isNull(selectedAccount, ErrorMessages.INPUT_NULL_MESSAGE);
		InputValidator.isNull(user,ErrorMessages.INPUT_NULL_MESSAGE);
		boolean isWithdrawSuccess = false;
		try {
			isWithdrawSuccess = transactionDao.withdraw(user,selectedAccount,amountToWithdraw);
		}catch(Exception e) {
			throw new CustomException("Error while Depositing Money!!",e);
		}
		return isWithdrawSuccess;
	}

	public boolean transferWithinBank(Account accountFromTransfer, Account accountToTransfer, double amountToTransfer) throws CustomException {
		InputValidator.isNull(accountFromTransfer, ErrorMessages.INPUT_NULL_MESSAGE);
		InputValidator.isNull(accountToTransfer,ErrorMessages.INPUT_NULL_MESSAGE);
		boolean isTransactionSuccess = false;
		try {
			isTransactionSuccess = transactionDao.transferMoneyWithinBank(accountFromTransfer,accountToTransfer,amountToTransfer);
		}catch(Exception e) {
			throw new CustomException("Error while Transferring Money!!"+e.getMessage(),e);
		}
		return isTransactionSuccess;
	}

}
