package com.banking.view;

import java.util.logging.Logger;

import com.banking.model.CustomerDetails;
import com.banking.utils.CustomException;
import com.banking.utils.ErrorMessages;
import com.banking.utils.InputValidator;

public class UserView {
	private static final Logger log = Logger.getLogger(UserView.class.getName());

	public void displaySuccessMessage() {
		log.info("User Created Successfully");
	}

	public void displayFailureMessage() {
		log.info("User Creation Failed!! Try Again");
	}

	public void displayUserDetails(CustomerDetails customerDetails) throws CustomException {
		InputValidator.isNull(customerDetails, ErrorMessages.INPUT_NULL_MESSAGE);
		//System.out.println(customerDetails);
		customerDetails.setUserId();
		customerDetails.setFirstName();
		customerDetails.setLastName();
		customerDetails.setGender();
		customerDetails.setEmail();
		customerDetails.setPan();
		customerDetails.setAadhar();
		customerDetails.setAccountId();
		customerDetails.setAccountNumber();
		customerDetails.setBalance();
	}

	public void displayUserDetailsFailedMessage() {
		log.info("Error While Reterving User Detail!! Please Try Again!!");
	}

}
